name: CI

on: 
  push:
    branches: 
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: login
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:login
      - name: configure
        uses: actions/heroku@master
        env:
          HEROKU_APP: ${{ secrets.HEROKU_APP }}
        with:
          args: git:remote -a $HEROKU_APP
      - name: release
        uses: actions/heroku@master
        if: github.ref == 'refs/heads/master' && job.status == 'success'
        run: git push heroku master