name: CI

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Deploy to Heroku
        env:
          HEROKU_USERNAME: ${{ secrets.USERNAME }}
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP: ${{ secrets.HEROKU_APP }}
        if: github.ref == 'refs/heads/master' && job.status == 'success'
        run: git push https://$HEROKU_USERNAME:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP.git origin/master:master