name: CI

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: deploy
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP: ${{ secrets.HEROKU_APP }}
        if: github.ref == 'refs/heads/master' && job.status == 'success'
        run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git origin/master:master
